### ISSUE TITLE
[Task] Upgrade ESN Sabre to Php 7.4

### ISSUE THREAD

**Issue by renaudboyer** [linagora/esn#44]
## Definition

Update ESN Sabre Php version to 7.4

To upgrade to Php 7.4, we need to update to Php-7.4-compliant dependencies including latest Sabre version.

## Tasks

* [x] Update Sabre/DAV dependency (4.1.5)
* [x] Rebase ESN VObject lib to the latest version (4.3.5)
* [x] Update standard dependencies to the latest version
* [x] Upgrade code to Php 7.4
* [x] Upgrage PhpUnit version
* [x] Fix tests
* [ ] Upgrade coding style according to [PSR-2](https://www.php-fig.org/psr/psr-2/)
* [ ] Update linters
